import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ThemeContextProvider } from "@/context/ThemeContext";
import NavBar from "@/components/navbar/NavBar";

const poppins = Poppins({
  weight: ["600"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Curious Expolorer",
  description: "Generated by create next app",
};

function Providers({ children }: any) {
  return <ThemeContextProvider>{children}</ThemeContextProvider>;
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body className={poppins.className}>
          <NavBar />
          {children}
        </body>
      </html>
    </Providers>
  );
}
